export const GET_PRODUCTS="GET_PRODUCTS";
export const LOAD_PRODUCTS="LOAD_PRODUCTS";
export const FAIL_PRODUCTS="FAIL_PRODUCTS";
export const GET_PRODUCT="GET_PRODUCT";
export const FAIL_PRODUCT= "FAIL_PRODUCT";
export const LOAD_PRODUCT= "LOAD_PRODUCT";